languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = "true"
enableEmoji = "true"
relativeURLs = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://resume.l0v0.com/"
title = "梁伟添的个人简历"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#99cdf4"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#e6e6e6"
colorSecondary = "#aaa"
pages = 1

# Multi language support
[languages]
  [languages.en]
    languageName = 'en'
    title = "TimmyLiang Personal Resume"
    weight = 1
  [languages.zh]
    languageName = 'zh'
    title = "梁伟添的个人简历"
    weight = 2
